CREATE TABLE MUSICIAN (
    nickname VARCHAR(16) NOT NULL,
    firstName VARCHAR(20) NOT NULL,
    lastName VARCHAR(20) NOT NULL, 
    e_mail VARCHAR(100) UNIQUE,
    locality VARCHAR(16) NOT NULL, 
    bestInstrument VARCHAR(16) NOT NULL,
    telephoneNumber VARCHAR(16) NOT NULL,
    isCertified BIT NOT NULL,
    isMaster BIT NOT NULL,
    PRIMARY KEY (nickname)
);

CREATE TABLE GENRE(
    genreName VARCHAR(16) NOT NULL,
    genreDescription VARCHAR(128) NOT NULL,
    origin VARCHAR(256) NOT NULL,
    nickname VARCHAR(16) NOT NULL FOREIGN KEY REFERENCES MUSICIAN
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    PRIMARY KEY (genreName); 
)

CREATE TABLE INFLUENCE(
    genreName VARCHAR(16) NOT NULL FOREIGN KEY REFERENCES MUSICIAN
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    nickname VARCHAR(16) NOT NULL FOREIGN KEY REFERENCES MUSICIAN
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    PRIMARY(genreName, nickname)
)

CREATE TABLE FOLLOW(
    genreName VARCHAR(16) NOT NULL FOREIGN KEY REFERENCES MUSICIAN
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    nickname VARCHAR(16) NOT NULL FOREIGN KEY REFERENCES MUSICIAN
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    PRIMARY(genreName, nickname)
)

CREATE TABLE DISCUSSION(
    discussionID VARCHAR(16) NOT NULL,
    
)
