DROP TABLE IF EXISTS _USER;

CREATE TABLE _USER(
  ID INT PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  PASS VARCHAR(20) NOT NULL
);

INSERT INTO _USER (ID, FIRST_NAME, LAST_NAME, PASS)
VALUES (1, 'John', 'Doe', 'paaaa');

INSERT INTO _USER (ID, FIRST_NAME, LAST_NAME, PASS)
VALUES (2, 'Alice', 'Wonderland', 'eeeeeeee');