DROP TABLE IF EXISTS _POST;

CREATE TABLE _POST(
  ID INT PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL
);

INSERT INTO _POST (ID, FIRST_NAME, LAST_NAME)
VALUES (1, 'John', 'Doe');

INSERT INTO _POST (ID, FIRST_NAME, LAST_NAME)
VALUES (2, 'Alice', 'Wonderland');